[build]
external_node_modules = [
    "express",
    "express-async-errors",
    "cors",
    "dotenv",
    "serverless-http",
    "body-parser",
    "mongoose",
]
node_bundler = "esbuild"
functions = "functions"
